version: 0.2

phases:
  install:
#    runtime-versions:
#      docker: 19
    commands:
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --short --client
      - echo Installing AWS IAM Authenticator...
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo  dckr_pat_s84GmhpEleCFl0giHWeeQWxDj-Q | docker login --username zarmeena --password-stdin
      - docker build -t ci-cd-pipeline .
      - docker tag ci-cd-pipeline:latest 071963907310.dkr.ecr.us-east-1.amazonaws.com/ci-cd-pipeline:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 071963907310.dkr.ecr.us-east-1.amazonaws.com
      - docker images
      - docker push 071963907310.dkr.ecr.us-east-1.amazonaws.com/ci-cd-pipeline:latest || (echo "docker push failed" && exit 1)
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name eks
      - kubectl config current-context
      - kubectl get nodes
      - echo Deploying to Kubernetes cluster...
      - kubectl apply -f k8s-deployment.yml
      - kubectl replace --force -f k8s-deployment.yml
      - kubectl get deployment
  
